# Generated by Django 3.1.1 on 2020-10-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posto',
            name='nome',
            field=models.CharField(default='Posto', max_length=300),
        ),
        migrations.AddField(
            model_name='precos',
            name='etanol',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
