# Generated by Django 3.1.1 on 2020-10-31 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posto', '0002_auto_20201014_0138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Denuncia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denuncia', models.IntegerField(choices=[(1, 'Preço divulgado está diferente no estabelecimento'), (2, 'Posto não encontrado na localidade'), (3, 'Problemas com o atendimento'), (4, 'Outros')])),
                ('motivos', models.CharField(blank=True, max_length=100)),
                ('posto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denuncia', to='posto.posto')),
            ],
        ),
    ]
